### ISSUE TITLE
Pronalazak komponenata koje nedostaju

### ISSUE THREAD

**Issue by thewantedboss** [lukavidic/ColorSorter_A#1]
Trenutna lista komponenata:

- ace tracking sensor
- the steering gear (micro Servo 9g SG90)
- Red LED
- battery case
- HS-Key1B (key module)

![components](https://github.com/user-attachments/assets/12229648-0ed4-4abe-a71f-b07c4b9b4f7d)

Potreno je sljedeće:
Za realizaciju projekta Colour-Sorter neophodno je dopuniti postojeću listu komponenti dodatnim dijelovima koji će omogućiti detekciju boja.

**Comment by thewantedboss** [comment]
Ocjena je 4.

**Comment by AndjelaS997** [comment]
Ocjena  je 5.

**Comment by GeneralKenobi72** [comment]
Ocjena 5

**Comment by GeneralKenobi72** [comment]
Vrijeme izrade: 15 minuta
