### ISSUE TITLE
Analiza power supply šeme

### ISSUE THREAD

**Issue by thewantedboss** [lukavidic/ColorSorter_A#11]
U okviru ovog zadatka potrebno je analizirati šemu napajanja kako bi se osiguralo stabilno i pouzdano napajanje za sve komponente sistema. Na osnovu ove analize, donijeti odluku da li je potreban dodatni sklop za stabilizaciju i konverziju napona, ili su postojeći izvori napajanja adekvatni za zadate komponente.

**Comment by thewantedboss** [comment]
Ocjena 6.

**Comment by GeneralKenobi72** [comment]
Ocjena 6

**Comment by AndjelaS997** [comment]
Ocijna 6.

**Comment by AndjelaS997** [comment]
Ocjena 7.
