### ISSUE TITLE
Dodavanje pinova za programiranje (ICSP)

### ISSUE THREAD

**Issue by thewantedboss** [lukavidic/ColorSorter_A#12]
U ovom zadatku potrebno je dodati odgovarajuće pinove za programiranje mikrokontrolera koristeći ICSP (In-Circuit Serial Programming) interfejs, kako bi se omogućilo programiranje mikrokontrolera.

**Comment by thewantedboss** [comment]
Ocjena 4.

**Comment by GeneralKenobi72** [comment]
Ocjena 5

**Comment by AndjelaS997** [comment]
Ocijena 5.

**Comment by AndjelaS997** [comment]
Ocjena 4.

**Comment by AndjelaS997** [comment]
Vrijeme izrade 20min.
