### ISSUE TITLE
Analiza komunikacionih interfejsa

### ISSUE THREAD

**Issue by thewantedboss** [lukavidic/ColorSorter_A#13]
U okviru analize komunikacionih interfejsa potrebno je detaljno razmotriti sve metode komunikacije koje će mikrokontroler koristiti kako bi interagovao sa spoljnim uređajima.

**Comment by thewantedboss** [comment]
Ocjena 5.

**Comment by GeneralKenobi72** [comment]
Ocjena 7

**Comment by AndjelaS997** [comment]
Ocijena 6.

**Comment by AndjelaS997** [comment]
Ocjena je 6.

**Comment by AndjelaS997** [comment]
Ocjena je 7.
