### ISSUE TITLE
Izrada šeme minimalne konfiguracije u alatu KiCAD

### ISSUE THREAD

**Issue by GeneralKenobi72** [lukavidic/ColorSorter_A#14]
U alatu KiCAD spojiti šemu minimalne konfiguracije koja ukljucuje pinove MCLR, VCAP, VSS/VDD

**Comment by GeneralKenobi72** [comment]
Ocjena 6

**Comment by thewantedboss** [comment]
Ocjena 4.

**Comment by GeneralKenobi72** [comment]
Vrijeme izrade 30 minuta i 29 sekundi
