### ISSUE TITLE
Dodati Eksterni Oscilator

### ISSUE THREAD

**Issue by thewantedboss** [lukavidic/ColorSorter_A#18]
Potrebno je provjeriti tačnost, stabilnost i potrebnu brzinu oscilatora za ovaj mikrokontroler, a zatim odlučiti da li je interni oscilator dovoljan ili je bolje koristiti eksterni oscilator za precizne primjene.

**Comment by thewantedboss** [comment]
Ocjena 6.

**Comment by AndjelaS997** [comment]
Ocjena 6.

**Comment by GeneralKenobi72** [comment]
Ocjena 7

**Comment by AndjelaS997** [comment]
Ocjena je 7.

**Comment by GeneralKenobi72** [comment]
Vrijeme izrade 20 minuta
