### ISSUE TITLE
Dokumentovati sve postojeće komponente

### ISSUE THREAD

**Issue by thewantedboss** [lukavidic/ColorSorter_A#2]
Potrebno je u dokumentaciju uključiti sljedeće:

1. Postojeće komponente koje su se koristile/će se koristiti dalje za projekat
       - Lista komponenti
       - Opis funkcije svake komponente
       - Specifikacije komponenti
       - Šematski prikaz veze

**Comment by thewantedboss** [comment]
Ocjena 5.

**Comment by AndjelaS997** [comment]
Ocjena je 5.

**Comment by GeneralKenobi72** [comment]
Ocjena 6

**Comment by GeneralKenobi72** [comment]
Vrijeme izrade: 2h
