### ISSUE TITLE
Sklopiti komponente

### ISSUE THREAD

**Issue by thewantedboss** [lukavidic/ColorSorter_A#3]
U okviru ovog zadatka potrebno je sklopiti sve postojeće komponente u odgovarajući model koji će se koristiti kroz projekat.

**Comment by thewantedboss** [comment]
(Težina zadatka 1-veoma lako, 10-veoma teško)
Ocjena 3.

**Comment by AndjelaS997** [comment]
Ocjena 3.

**Comment by GeneralKenobi72** [comment]
Ocjena: 3

**Comment by GeneralKenobi72** [comment]
Vrijeme izrade zadatka: 40 minuta
