### ISSUE TITLE
Upoznati se sa Mikrokontrolerom (PIC24FJ64GA702)

### ISSUE THREAD

**Issue by thewantedboss** [lukavidic/ColorSorter_A#4]
Potrebno se upoznati  sa osnovnim karakteristikama, funkcionalnostima i mogućnostima mikrokontrolera.
Datasheet -> https://www.alldatasheet.com/datasheet-pdf/view/1424911/MICROCHIP/PIC24FJ64GA702.html

**Comment by thewantedboss** [comment]
Ocjena 6.

**Comment by AndjelaS997** [comment]
Ocijena 7.

**Comment by GeneralKenobi72** [comment]
Ocjena 6
