### ISSUE TITLE
Analiza napona napajanja mikrokontrolera

### ISSUE THREAD

**Issue by thewantedboss** [lukavidic/ColorSorter_A#5]
U okviru ovog zadatka potrebno je analizirati  Vdd, Vss pinove kao i AVdd i AVss pinove.
U okviru istog, u dokumentaciji treba obuhvatiti sve relevantne informacije o ovim pinovima, uključujući način povezivanja sa ostalim komponentama, kao i preporučene vrijednosti tih komponenata.

**Comment by thewantedboss** [comment]
Ocjena 5.

**Comment by AndjelaS997** [comment]
Ovijena 5.

**Comment by GeneralKenobi72** [comment]
Ocjena 4

**Comment by thewantedboss** [comment]
Vrijeme izrade 30min.
