### ISSUE TITLE
Analiza Master Clear Reset pina

### ISSUE THREAD

**Issue by thewantedboss** [lukavidic/ColorSorter_A#6]
U okviru ovog zadatka potrebno je analizirati pin Master Clear (MCLR), obraditi njegovu funkciju, način povezivanja i značaj za pravilno funkcionisanje mikrokontrolera. Takođe, u okviru navedenog, u dokumentaciji treba obuhvatiti sve relevantne informacije o ovom pinu, uključujući način povezivanja sa ostalim komponentama, kao i preporučene vrijednosti otpornika i napajanja.

**Comment by thewantedboss** [comment]
Ocjena 6.

**Comment by AndjelaS997** [comment]
Ocijena 7.

**Comment by GeneralKenobi72** [comment]
Ocjena 6

**Comment by GeneralKenobi72** [comment]
Vrijeme izrade: 40 minuta
