### ISSUE TITLE
Analiza Voltage Regulator Pin

### ISSUE THREAD

**Issue by thewantedboss** [lukavidic/ColorSorter_A#7]
U okviru ovog zadatka potrebno je analizirati Voltage Regulator Pin (VCAP) mikrokontrolera, istražujući njegovu funkciju i značaj za stabilnost naponskog sistema mikrokontrolera. U okviru zadatka, u dokumentaciji je potrebno uključiti odgovarajuće povezivanja ovog pina i objašnjenje njegovog značaja za cjelokupni rad mikrokontrolera.

**Comment by thewantedboss** [comment]
Ocjena 3.

**Comment by AndjelaS997** [comment]
Ocijena 3.

**Comment by GeneralKenobi72** [comment]
Ocjena 4
