### ISSUE TITLE
Upoznati se sa RGB senzorom, Wifi modulom

### ISSUE THREAD

**Issue by thewantedboss** [lukavidic/ColorSorter_A#8]
U ovom zadatku cilj je upoznati se sa RGB senzorom i WiFi modulom kako bi se razumijele njihove karakteristike, način rada, uključujući integraciju ova dva uređaja. 
Datasheet Color 10 Click -> https://docs.rs-online.com/04be/A700000009002027.pdf
Datasheet ESP8266EX -> https://www.espressif.com/sites/default/files/documentation/0a-esp8266ex_datasheet_en.pdf

**Comment by thewantedboss** [comment]
Ocjena 6.

**Comment by GeneralKenobi72** [comment]
Ocjena 7

**Comment by AndjelaS997** [comment]
Ocijena 6.

**Comment by GeneralKenobi72** [comment]
Vrijeme izrade zadatka 40 minuta

**Comment by AndjelaS997** [comment]
Ocjena 6.
